const languageCodes = {
    "afrikaans": "AF",
    "albanian": "SQ",
    "amharic": "AM",
    "armenian": "HY",
    "assamese": "AS",
    "aymara": "AY",
    "azerbaijani": "AZ",
    "bambara": "BM",
    "basque": "EU",
    "belarusian": "BE",
    "bengali": "BN",
    "bhojpuri": "BHO",
    "bosnian": "BS",
    "catalan": "CA",
    "cebuano": "CEB",
    "chichewa": "NY",
    "chinese (simplified)": "ZH-CN",
    "chinese (traditional)": "ZH-TW",
    "corsican": "CO",
    "croatian": "HR",
    "dhivehi": "DV",
    "dogri": "DOI",
    "dutch": "NL",
    "english": "EN",
    "esperanto": "EO",
    "estonian": "ET",
    "ewe": "EE",
    "filipino": "TL",
    "finnish": "FI",
    "french": "FR",
    "frisian": "FY",
    "galician": "GL",
    "georgian": "KA",
    "german": "DE",
    "greek": "EL",
    "guarani": "GN",
    "gujarati": "GU",
    "haitian creole": "HT",
    "hausa": "HA",
    "hawaiian": "HAW",
    "hebrew": "IW",
    "hindi": "HI",
    "hmong": "HMN",
    "hungarian": "HU",
    "icelandic": "IS",
    "igbo": "IG",
    "ilocano": "ILO",
    "indonesian": "ID",
    "irish": "GA",
    "italian": "IT",
    "japanese": "JA",
    "javanese": "JW",
    "kannada": "KN",
    "kazakh": "KK",
    "khmer": "KM",
    "kinyarwanda": "RW",
    "konkani": "GOM",
    "korean": "KO",
    "krio": "KRI",
    "kurdish (kurmanji)": "KU",
    "kurdish (sorani)": "CKB",
    "kyrgyz": "KY",
    "lao": "LO",
    "latin": "LA",
    "latvian": "LV",
    "lingala": "LN",
    "lithuanian": "LT",
    "luganda": "LG",
    "luxembourgish": "LB",
    "macedonian": "MK",
    "maithili": "MAI",
    "malagasy": "MG",
    "malay": "MS",
    "malayalam": "ML",
    "maltese": "MT",
    "maori": "MI",
    "meiteilon (manipuri)": "MNI-MTEI",
    "mizo": "LUS",
    "mongolian": "MN",
    "myanmar (burmese)": "MY",
    "nepali": "NE",
    "norwegian": "NO",
    "odia (oriya)": "OR",
    "oromo": "OM",
    "pashto": "PS",
    "persian": "FA",
    "polish": "PL",
    "portuguese": "PT",
    "punjabi": "PA",
    "quechua": "QU",
    "romanian": "RO",
    "russian": "RU",
    "samoan": "SM",
    "sanskrit": "SA",
    "scots gaelic": "GD",
    "sepedi": "NSO",
    "serbian": "SR",
    "sesotho": "ST",
    "shona": "SN",
    "sindhi": "SD",
    "sinhala": "SI",
    "slovak": "SK",
    "slovenian": "SL",
    "somali": "SO",
    "spanish": "ES",
    "sundanese": "SU",
    "swahili": "SW",
    "swedish": "SV",
    "tajik": "TG",
    "tamil": "TA",
    "tatar": "TT",
    "telugu": "TE",
    "thai": "TH",
    "tigrinya": "TI",
    "tsonga": "TS",
    "turkish": "TR",
    "turkmen": "TK",
    "twi": "AK",
    "ukrainian": "UK",
    "urdu": "UR",
    "uyghur": "UG",
    "uzbek": "UZ",
    "vietnamese": "VI",
    "welsh": "CY",
    "xhosa": "XH",
    "yiddish": "YI",
    "yoruba": "YO",
    "zulu": "ZU"
};

export default languageCodes;
